wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("search/<str:search>", views.search, name="search"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("new", views.new, name="new"),
    path("edit", views.edit, name="edit"),
    path("rand", views.rand, name="rand"),
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/views.py
from django.shortcuts import render, redirect
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
from . import util
from markdown2 import markdown
import random

class SearchForm(forms.Form):
    search = forms.CharField(label="Search")

class NewEntryForm(forms.Form):
    title = forms.CharField(label="Title")
    content = forms.CharField(widget=forms.Textarea)

class EditEntryForm(forms.Form):
    title = forms.CharField(widget=forms.HiddenInput(), required = False)
    content = forms.CharField(widget=forms.Textarea)

def index(request):
    if request.method == "POST":
        form = SearchForm(request.POST)
        if form.is_valid():
            search = form.cleaned_data["search"]
            all_entries = util.list_entries()
            if search in all_entries:
                return redirect("wiki:entry", search)
            else:
                return redirect("wiki:search", search)

    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "form": SearchForm(),
    })

def search(request, search):
    all_entries = util.list_entries()
    if search in all_entries:
        return redirect("wiki:entry", search)
    related_entries = []
    for entry in all_entries:
        if search in entry:
            related_entries += [entry]
    return render(request, "encyclopedia/search.html", {
        "title": search,
        "entries": related_entries,
        "form": SearchForm(),
    })

def entry(request, title):
    entry = util.get_entry(title)
    if entry != None:
        html_entry = markdown(entry)
        return render(request, "encyclopedia/entry.html", {
            "title": title,
            "entry": html_entry,
            "form": SearchForm(),
        })
    else:
        return render(request, "encyclopedia/404.html", {
            "title": title,
            "form": SearchForm(),
        })

def new(request):
    if request.method == "POST":
        form = NewEntryForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            all_entries = util.list_entries()
            if title in all_entries:
                return render(request, "encyclopedia/new.html", {
                    "new_entry": NewEntryForm(request.POST),
                    "form": SearchForm(),
                    "error_message": True,
                })
            else:
                content = form.cleaned_data["content"]
                util.save_entry(title, content)
                return redirect("wiki:entry", title)
    
    return render(request, "encyclopedia/new.html", {
            "new_entry": NewEntryForm(),
            "form": SearchForm(),
            "error_message": False,
        })

def edit(request):
    if request.method == "POST":
        form = EditEntryForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            util.save_entry(title, content)
            return redirect("wiki:entry", title)
    title = request.GET['entry']
    all_entries = util.list_entries()
    if title not in all_entries:
        return redirect("wiki:index")
    content = util.get_entry(title)
    return render(request, "encyclopedia/edit.html", {
        "title": title,
        "edit_entry": EditEntryForm({'title': title, 'content': content}),
        "form": SearchForm,
    })

def rand(request):
    all_entries = util.list_entries()
    rand_id = random.randint(0, len(all_entries) - 1)
    return redirect("wiki:entry", all_entries[rand_id])

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Entry
{% endblock %}

{% block body %}

    <h1>Edit Entry: {{ title }}</h1>

    <form action="{% url 'wiki:edit' %}" method="post">
        {% csrf_token %}
        {{ edit_entry }}
        <input type="submit" value="Save">
    </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}

    {{ entry |safe}}

    <form action="{% url 'wiki:edit' %}" method="GET">
        <input type="hidden" name="entry" value="{{ title }}">
        <input type="submit" value="Edit">
    </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'wiki:entry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="./../../static/encyclopedia/styles.css" rel="stylesheet">
    </head>
    <body>
        <div class="page-wrap">
            <div class="sidebar">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:index' %}" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:new' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:rand' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main-page">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create New Page
{% endblock %}

{% block body %}

    <h1>Create New Page</h1>

    <form action="{% url 'wiki:new' %}" method="post">
        {% csrf_token %}
        {{ new_entry }}
        <input type="submit" value="Save New Entry">
    </form>

    {% if error_message %}
        <p style="color: red; padding-left: 15px;">This page already exists. Change the title of this entry or edit the original page.</p>
    {% endif %}
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia - Search
{% endblock %}

{% block body %}
    <h1>Related Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'wiki:entry' entry %}">{{ entry }}</a></li>
        {% empty %}
            <li>We don't have any entry related to {{ title }}</li>
        {% endfor %}
    </ul>

{% endblock %}